export type TaskStatus = 'todo' | 'doing' | 'done' | 'blocked'
export type TaskPriority = 'low' | 'medium' | 'high' | 'critical'
export type WorkloadLevel = 'overload' | 'balanced' | 'underload'

export interface Team {
  id: string
  name: string
  category: string | null
  created_at: string
}

export interface Member {
  id: string
  name: string
  email: string | null
  team_id: string | null
  avatar_url: string | null
  created_at: string
}

export interface Task {
  id: string
  title: string
  team_id: string | null
  owner_id: string | null
  status: TaskStatus
  priority: TaskPriority
  due_date: string | null
  progress: number
  effort_days: number
  created_at: string
  updated_at: string
}

export interface TaskWithRelations extends Task {
  team: Team | null
  owner: Member | null
}

export interface MemberWorkload {
  member: Member
  openTaskCount: number
  totalEffortDays: number
  overdueCount: number
  weightedRemainingEffort: number
  loadScore: number
  level: WorkloadLevel
  reason: string
  suggestedAction: string
}

export interface TeamWorkloadSummary {
  team: Team
  avgLoadScore: number
  overloadCount: number
  balancedCount: number
  underloadCount: number
  memberCount: number
}

export interface WeeklyTrendPoint {
  week: string
  closed: number
}

export interface AiSummaryResult {
  summary: string
  generated_at: string
  /** 'fallback' means this text was built locally from raw numbers, not actually generated by AI. */
  source: 'ai' | 'fallback'
  /** User-facing explanation of the source — why it fell back, or a confidence caveat when it's real AI. */
  confidence_note: string
}

/** REQ-AI: per-owner numbers sent to the AI — the model only explains these, never computes them. */
export interface OwnerWorkloadSummaryInput {
  owner: string
  openTaskCount: number
  loadScore: number
  status: WorkloadLevel
  overdueCount: number
  topRiskTasks: string[]
}

/** REQ-AI: team-level numbers sent to the AI for the cross-team workload narrative. */
export interface TeamWorkloadSummaryInput {
  teams: Array<{
    team: string
    memberCount: number
    avgLoadScore: number
    overloadCount: number
    balancedCount: number
    underloadCount: number
  }>
  topOverloadedMembers: string[]
}

/** Prompt Direction output shape: summary + risk_reason + suggested_action + confidence_note. */
export interface AiWorkloadInsight {
  summary: string
  risk_reason: string
  suggested_action: string
  confidence_note: string
  source: 'ai' | 'fallback'
  generated_at: string
}
